services:
  db:
    image: postgres:18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 1s
      interval: 1s
      retries: 10

  my-app:
    image: my-app:latest
    container_name: my_app_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - NOTIFICATION_SERVICE_URL=http://notification-app:8081
    depends_on:
      db:
        condition: service_healthy

  notification-app:
    image: notification-app:latest
    container_name: notification_app_container
    ports:
      - "8081:8081"