apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: mongo-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
          image: notification-service:1.0
          name: notification-service-container
          volumeMounts:
            - mountPath: /config
              name: notification-service-config
      volumes:
        - name: notification-service-config
          configMap:
            name: notification-service-config
      restartPolicy: Always
