apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: book-service-secret
                  key: spring.datasource.password

---
apiVersion: v1
kind: Service
metadata:
  name: book-service-svc
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
