apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  labels:
    app: book-service
data:
  spring.datasource.url: jdbc:postgresql://book-db-svc:5432/book-db
  spring.datasource.username: user